# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30)),
                ('buyer', models.CharField(max_length=30)),
                ('cellphone', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('value', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('ip', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('buyed_time', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=30)),
                ('shiped_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '訂單',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('firm', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('product_content', models.TextField()),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '產品',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name': '產品圖',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
