# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '訂單', 'verbose_name_plural': '訂單'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '產品', 'verbose_name_plural': '產品'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': '產品圖', 'verbose_name_plural': '產品圖'},
        ),
        migrations.AlterField(
            model_name='product',
            name='firm',
            field=models.CharField(max_length=30, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, verbose_name='產品名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='價格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_content',
            field=models.TextField(verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.CharField(max_length=30, verbose_name='產品編號'),
        ),
    ]
