# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171007_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='static/images/slideshow')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.CharField(max_length=30, verbose_name='訂購人'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cellphone',
            field=models.CharField(max_length=20, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=30, verbose_name='訂單號碼'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(verbose_name='單價'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='產品'),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.PositiveIntegerField(verbose_name='總價'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='static/images', verbose_name='產品圖'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='產品名'),
        ),
    ]
