# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171009_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='Page',
            field=models.CharField(choices=[('1', 'First Slide'), ('2', 'Second Slide'), ('3', 'Third Slide')], default=1, max_length=1),
        ),
    ]
