# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_slideshow_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slideshow',
            old_name='Page',
            new_name='page',
        ),
    ]
