# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171009_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=40, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='mail',
            field=models.EmailField(default=1, max_length=254, verbose_name='信箱'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default=1, max_length=30, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyed_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='訂單時間'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.CharField(default=1, max_length=30, verbose_name='訂購人'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cellphone',
            field=models.CharField(default=1, max_length=20, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default=1, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=1, max_length=30, verbose_name='訂單號碼'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='單價'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='產品'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shiped_time',
            field=models.DateTimeField(auto_now=True, verbose_name='出貨時間'),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.PositiveIntegerField(default=1, verbose_name='總價'),
        ),
    ]
