# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171013_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='payment_way',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mail',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=200, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='總價'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyed_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default=1, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=1, max_length=50, verbose_name='訂單號碼'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shiped_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.PositiveIntegerField(default=1, verbose_name='數量'),
        ),
    ]
